// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3ZDzcHx2JLpdvNgm8eXwduGGIT3YoVcg',
    appId: '1:262898799859:web:f0ca95b1a2e139ae99d386',
    messagingSenderId: '262898799859',
    projectId: 'safeher-13e5f',
    authDomain: 'safeher-13e5f.firebaseapp.com',
    storageBucket: 'safeher-13e5f.firebasestorage.app',
    measurementId: 'G-XCVYY822S4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVgNmBMvqWqFRgim_gBru6ZfOUj8DEq3Y',
    appId: '1:262898799859:android:903a0b514721ad0c99d386',
    messagingSenderId: '262898799859',
    projectId: 'safeher-13e5f',
    storageBucket: 'safeher-13e5f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuNukg6HGl9nKWin5MZUIuP0tkMVRh9Ss',
    appId: '1:262898799859:ios:d3791220635ae77099d386',
    messagingSenderId: '262898799859',
    projectId: 'safeher-13e5f',
    storageBucket: 'safeher-13e5f.firebasestorage.app',
    iosBundleId: 'com.example.safeHer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuNukg6HGl9nKWin5MZUIuP0tkMVRh9Ss',
    appId: '1:262898799859:ios:d3791220635ae77099d386',
    messagingSenderId: '262898799859',
    projectId: 'safeher-13e5f',
    storageBucket: 'safeher-13e5f.firebasestorage.app',
    iosBundleId: 'com.example.safeHer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3ZDzcHx2JLpdvNgm8eXwduGGIT3YoVcg',
    appId: '1:262898799859:web:27e92b57bd9c974d99d386',
    messagingSenderId: '262898799859',
    projectId: 'safeher-13e5f',
    authDomain: 'safeher-13e5f.firebaseapp.com',
    storageBucket: 'safeher-13e5f.firebasestorage.app',
    measurementId: 'G-2LWFNG00X2',
  );
}
